In [2]:
import numpy as np
list1 = [1, 2, 3]
arr1 = np.array(list1)
arr1

array([1, 2, 3])

In [4]:
np.zeros(3)

array([0., 0., 0.])

In [6]:
# 2차원
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
# np.arange([시작번호], 끝번호, [건너뛰는 수])
# 끝번호가 필수값이다 ;; 인자 순서 왜저럼 ?
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(20, 30, 2)

array([20, 22, 24, 26, 28])

In [11]:
np.random.rand(2, 3)

array([[0.22396885, 0.95756302, 0.64242724],
       [0.85872452, 0.4458241 , 0.25006643]])

In [14]:
arr2 = np.arange(16)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [16]:
arr2.reshape(4, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [17]:
arr2.reshape(2,2, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [18]:
arr = np.arange(16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [19]:
arr.shape

(16,)

In [20]:
arr.dtype

dtype('int32')

In [21]:
arr.astype(float)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15.])

In [22]:
arr=np.arange(16)

In [23]:
arr[5]

5

In [24]:
arr[-1]

15

In [25]:
arr[5:8]

array([5, 6, 7])

In [30]:
arr = np.arange(16).reshape((4,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [31]:
arr[1]

array([4, 5, 6, 7])

In [32]:
arr[1, 2]

6

In [33]:
arr[0:2, 2:4]

array([[2, 3],
       [6, 7]])

In [34]:
arr[:2, 2:]

array([[2, 3],
       [6, 7]])

In [38]:
scores = [80, 90, 70, 75, 95, 65, 86, 75]
score_arr = np.array(scores)
score_arr

array([80, 90, 70, 75, 95, 65, 86, 75])

In [39]:
score_arr >= 90

array([False,  True, False, False,  True, False, False, False])

In [40]:
score_arr[score_arr >=90]

array([90, 95])

In [42]:
score_arr[score_arr >= 90] = 999
score_arr

array([ 80, 999,  70,  75, 999,  65,  86,  75])

In [43]:
arr = np.arange(16).reshape((4,4))
arr[:2, 2:]

array([[2, 3],
       [6, 7]])

In [44]:
scores = [80, 90, 70, 75, 95, 65, 86, 75]
score_arr = np.array(scores)
score_arr[score_arr >= 90] = 999
score_arr

array([ 80, 999,  70,  75, 999,  65,  86,  75])

In [47]:
arr = np.arange(10).reshape(2, 5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [49]:
# arr.transpose() 와 동일함. 와 이런 축약형이 있다고 ?
arr.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [51]:
arr3d = np.arange(27).reshape(3, 3, 3)
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [53]:
arr3d.T # transpose(2,1,0)과 동일함

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [58]:
arr = np.arange(10).reshape(2, 5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [59]:
np.save('array_name', arr) # 저장

In [61]:
load_arr = np.load('array_name.npy') # 불러오기
load_arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])